# Generated by Django 5.1.1 on 2024-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.TextField(default='Aaron'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Aaron'),
            preserve_default=False,
        ),
    ]
