# Generated by Django 5.1.3 on 2024-11-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='couse',
            new_name='course',
        ),
    ]
