# Generated by Django 5.1.3 on 2024-11-16 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_couse_schedule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(default='Schedule 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
