# Generated by Django 5.1.3 on 2024-11-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_review_title_schedule_student_schedule_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.AddField(
            model_name='schedule',
            name='course',
            field=models.ManyToManyField(to='project.course'),
        ),
    ]
