# Generated by Django 5.1.3 on 2024-11-22 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_schedule_course_schedule_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.course')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='project.schedule')),
            ],
        ),
    ]
