# Generated by Django 5.1.3 on 2024-11-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
    ]
