# Generated by Django 5.1.3 on 2024-12-08 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_schedule_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='satisfaction',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
