# Generated by Django 5.1.3 on 2024-12-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_review_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.TextField(default='Boston University'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subschool',
            field=models.TextField(default='CAS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.TextField(default='Boston University'),
            preserve_default=False,
        ),
    ]
